name: data_channel
description: data_channel (DC) is a simple dart utility for handling exceptions and data routing.
version: 3.0.0+2
homepage: https://github.com/ganeshrvel/pub-data-channel

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  #

dev_dependencies:
  # Linting
  very_good_analysis: ^10.1.0
  test: ^1.25.0
