name: data_channel
description: data_channel (DC) is a simple dart utility for handling exceptions and data routing.
version: 4.1.0
homepage: https://github.com/ganeshrvel/pub-data-channel

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.17.0

dev_dependencies:
  # Linting
  very_good_analysis: ^10.1.0
  test: ^1.25.0
